# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64ec51d36e96ba279c89b1117f37ac0728bf0c5ecb96c50fa724971ea668394b20bd89ddb639e1c453d0f40ea15fb77ae41ebcc9ef00179158ca1a8cdccf3d42

test:
  secret_key_base: 13bc7dd965327c97e98140a56b9d4f5e6fa123f7d89cf42d6c3df44dab4e699a0fd41e8e3a6518b2a5d2b30b3ff2cbc8ea97ad4db9eda7685da7f3ea083f69ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
